{% set name = "marpyter" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marpyter-{{ version }}.tar.gz
  sha256: b3b631988bbbd35b2c44e1b00c227f3bbe9ca242a09601147958f0f46b46defa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3

test:
  imports:
    - marpyter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trungleduc/marpyter
  summary: A JupyterLab extension for Marp.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
